Sales\Receipts\Products\Code\Tables\Products:
  table: sales_receipts_products
  type: entity
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    product_id:
      name: product_id
      type: integer
      length: 11
      nullable: false
    receipt_id:
      name: receipt_id
      type: integer
      length: 11
      nullable: false
    quantity:
      name: quantity
      type: integer
      length: 11
      nullable: true
    unit_price:
      name: unit_price
      type: integer
      length: 11
      nullable: true
    created_by:
      name: created_by
      type: integer
      length: 11
      nullable: true
    date_created:
      name: date_created
      type: datetime
      nullable: true
    modified_by:
      name: modified_by
      type: integer
      length: 11
      nullable: true
    date_modified:
      name: date_modified
      type: datetime
      nullable: true
  indexes:
    product_id_index:
      columns: [product_id]
    receipt_id_index:
      columns: [receipt_id]
  lifecycleCallbacks:
    prePersist:
      - onPrePersist
      - onPrePersistCallbacks
    preUpdate:
      - onPreUpdate
      - onPreUpdateCallbacks
